# Generated by Django 4.2.7 on 2025-07-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'URL Mapping',
                'verbose_name_plural': 'URL Mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=1000)),
                ('url_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.urlmapping')),
            ],
            options={
                'verbose_name': 'Click Analytics',
                'verbose_name_plural': 'Click Analytics',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
